### ISSUE TITLE
Do cloud billing upto end of Q3 2023

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3350] opened 2023-10-31 15:12 UTC
I'll work with @colliand in doing cloud billing, upto Q3 of 2023 (until end of September 2023).

This entails:

- [ ] Cloud costs for AWS clusters we need to pass through
- [ ] Cloud costs for GCP clusters we need to pass through
- [ ] Cloud costs for hubs on 'shared' clusters
   - [ ] For `2i2c` GCP cluster
   - [ ] For `2i2c-aws-us` AWS cluster
   - [ ] For `2i2c-gcp-uk` GCP cluster

I'll start working on this sometime early November.

Process improvements

- https://github.com/2i2c-org/infrastructure/issues/3386

**Comment by choldgraf** [comment] 2023-10-31 23:39
If it's a useful datapoint, it looks like we have about $70,000 of un-billed cloud costs right now, based on our AirTable graph. I don't know if that's an exact number, but maybe is a ballpark.

![CleanShot 2023-10-31 at 16 38 46@2x](https://github.com/2i2c-org/infrastructure/assets/1839645/d584de25-f575-49d5-a5e4-06d6ea8e4af7)

**Comment by yuvipanda** [comment] 2023-11-01 05:44
ooof that is a lot of money.

**Comment by damianavila** [comment] 2023-11-01 19:56
Copy-pasting some thoughts I shared from Slack (that I think it would be useful to record here as well):

> Can we make sure we (at least briefly) document the process in that very issue so other engineers (besides @yuvipanda) can help with this recurring process in the future? Thanks!

**Comment by yuvipanda** [comment] 2023-11-10 17:14
Another goal is to build out some more infrastructure to make this easier next time.

https://github.com/2i2c-org/infrastructure/pull/3397 tags nodes appropriately so we can easily differentiate between core and user and dask worker nodes.

**Comment by yuvipanda** [comment] 2023-11-17 10:51
Moved to https://github.com/2i2c-org/meta/issues/742

**Comment by consideRatio** [comment] 2023-11-17 12:19
Closing this as the issue is otherwise duplicated with https://github.com/2i2c-org/meta/issues/742, and I think the intent was to close this.

**Closed by consideRatio** 2023-11-17 12:19 UTC
