### ISSUE TITLE
Provide a single source of truth for which *images* we are responsible for maintaining

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#3690] opened 2024-02-02 21:21 UTC
We maintain images for some communities, and some communities maintain their own images. Currently, there is no source of truth for this.

We should have one.

**Comment by yuvipanda** [comment] 2024-02-02 21:22
As suggested by @GeorgianaElena  in https://github.com/2i2c-org/infrastructure/pull/3684#discussion_r1475747055, one possible quick space is to look at images within our org (https://github.com/2i2c-org?q=image&type=all&language=&sort=)

**Comment by jnywong** [comment] 2024-04-09 13:37
Related to https://github.com/2i2c-org/meta/issues/846

**Comment by consideRatio** [comment] 2024-04-10 05:54
Very related - i'll go for a close here as a duplicate of the issue you linked @jnywong!

**Closed by consideRatio** 2024-04-10 05:54 UTC
Labels: allocation:internal-eng
