### ISSUE TITLE
Document how to setup GPU access for hubs

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#1250] opened 2022-04-27 01:44 UTC
### Context

Currently, we support GPUs on Azure and GCP. However, this is not really documented. We should.

**Comment by sgibson91** [comment] 2022-04-27 06:56
This is a duplicate of https://github.com/2i2c-org/infrastructure/issues/996 so I'll close

**Closed** 2022-04-27 06:57 UTC
