### ISSUE TITLE
Investigate AzureAD login issues with utoronto

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2628] opened 2023-06-08 21:18 UTC
### Context

Reported via freshdesk https://2i2c.freshdesk.com/a/tickets/764

### Updates and actions

<details><summary>log grep for 500</summary>
<p>
```
ovyan@hub-749bb69658-fpk6n:/srv/jupyterhub$ tail -10000 jupyterhub.log | grep \]\ 500
[E 2023-06-08 20:12:29.357 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.4) 160.73ms
[E 2023-06-08 20:41:24.749 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.7) 220.95ms
[E 2023-06-08 20:41:44.609 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.7) 140.10ms
[E 2023-06-08 20:49:14.602 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 331.61ms
jovyan@hub-749bb69658-fpk6n:/srv/jupyterhub$ tail -20000 jupyterhub.log | grep \]\ 500
[W 2023-06-08 19:33:47.616 JupyterHub web:1796] 500 GET /hub/user/2c94f0af-dd06-4e88-8563-a6bfa646d6aa/rstudio/?redirects=2 (10.1.0.5): Redirect loop detected. Notebook has jupyterhub version 3.1.0, but the Hub expects 3.1.1. Try installing jupyterhub==3.1.1 in the user environment if you continue to have problems.
[E 2023-06-08 19:33:47.617 JupyterHub log:186] 500 GET /hub/user/2c94f0af-dd06-4e88-8563-a6bfa646d6aa/rstudio/?redirects=2 (2c94f0af-dd06-4e88-8563-a6bfa646d6aa@10.1.0.5) 2.87ms
[E 2023-06-08 19:46:00.632 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.10) 258.97ms
[E 2023-06-08 19:59:35.308 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.4) 631.53ms
[E 2023-06-08 20:12:03.539 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.9) 226.09ms
[E 2023-06-08 20:12:29.357 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.4) 160.73ms
[E 2023-06-08 20:41:24.749 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.7) 220.95ms
[E 2023-06-08 20:41:44.609 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.7) 140.10ms
[E 2023-06-08 20:49:14.602 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 331.61ms
jovyan@hub-749bb69658-fpk6n:/srv/jupyterhub$ tail -50000 jupyterhub.log | grep \]\ 500
[E 2023-06-08 17:14:17.719 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.8) 160.46ms
[E 2023-06-08 17:14:46.689 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.14) 175.70ms
[E 2023-06-08 17:16:34.925 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 192.54ms
[E 2023-06-08 17:16:46.842 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 224.42ms
[E 2023-06-08 17:17:02.691 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 137.63ms
[E 2023-06-08 17:17:19.268 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 207.07ms
[E 2023-06-08 17:17:20.087 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 195.35ms
[E 2023-06-08 17:17:24.486 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 128.78ms
[E 2023-06-08 17:17:59.134 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.14) 200.27ms
[E 2023-06-08 17:18:32.520 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 208.24ms
[E 2023-06-08 17:18:38.091 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 163.02ms
[E 2023-06-08 17:18:44.920 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 170.81ms
[E 2023-06-08 17:18:47.708 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 181.25ms
[E 2023-06-08 17:18:50.077 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 168.56ms
[E 2023-06-08 17:19:14.801 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 267.95ms
[E 2023-06-08 17:19:35.747 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 162.76ms
[E 2023-06-08 17:20:02.200 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 149.38ms
[E 2023-06-08 17:20:12.738 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.9) 168.12ms
[E 2023-06-08 17:20:14.807 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 145.61ms
[E 2023-06-08 17:20:34.674 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 163.03ms
[E 2023-06-08 17:20:52.493 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 178.09ms
[E 2023-06-08 17:23:14.392 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.4) 255.13ms
[E 2023-06-08 17:24:34.919 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 141.01ms
[E 2023-06-08 17:24:41.219 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.10) 216.93ms
[E 2023-06-08 17:27:05.948 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 191.61ms
[E 2023-06-08 17:28:01.865 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.4) 505.16ms
[E 2023-06-08 17:28:20.708 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 182.80ms
[E 2023-06-08 17:28:31.024 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 135.73ms
[E 2023-06-08 17:29:42.582 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.9) 147.06ms
[E 2023-06-08 17:30:59.162 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 357.22ms
[E 2023-06-08 17:31:23.669 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.14) 205.90ms
[E 2023-06-08 17:42:17.237 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.14) 221.38ms
[E 2023-06-08 17:42:51.309 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.14) 138.36ms
[E 2023-06-08 17:43:15.543 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.14) 141.55ms
[E 2023-06-08 17:43:36.816 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 134.59ms
[E 2023-06-08 17:44:07.522 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 160.12ms
[E 2023-06-08 17:44:11.469 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 251.03ms
[E 2023-06-08 18:04:16.125 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 274.32ms
[E 2023-06-08 18:06:59.776 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.9) 361.96ms
[E 2023-06-08 18:07:06.278 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.9) 220.45ms
[E 2023-06-08 18:07:10.470 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.9) 143.28ms
[E 2023-06-08 18:09:30.157 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 234.91ms
[E 2023-06-08 18:09:35.034 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 150.76ms
[E 2023-06-08 18:09:39.838 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.5) 158.44ms
[E 2023-06-08 18:11:03.025 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.4) 142.81ms
[E 2023-06-08 18:24:47.559 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.7) 335.65ms
[E 2023-06-08 18:31:54.783 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.14) 295.95ms
[E 2023-06-08 18:32:25.630 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.10) 215.90ms
[E 2023-06-08 18:32:55.716 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.10) 158.22ms
[E 2023-06-08 18:33:10.285 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.10) 137.49ms
[E 2023-06-08 18:33:17.150 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.7) 140.13ms
[E 2023-06-08 18:34:16.914 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.14) 134.23ms
[E 2023-06-08 18:34:51.073 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 272.04ms
[E 2023-06-08 19:03:18.088 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 154.11ms
[W 2023-06-08 19:33:47.616 JupyterHub web:1796] 500 GET /hub/user/2c94f0af-dd06-4e88-8563-a6bfa646d6aa/rstudio/?redirects=2 (10.1.0.5): Redirect loop detected. Notebook has jupyterhub version 3.1.0, but the Hub expects 3.1.1. Try installing jupyterhub==3.1.1 in the user environment if you continue to have problems.
[E 2023-06-08 19:33:47.617 JupyterHub log:186] 500 GET /hub/user/2c94f0af-dd06-4e88-8563-a6bfa646d6aa/rstudio/?redirects=2 (2c94f0af-dd06-4e88-8563-a6bfa646d6aa@10.1.0.5) 2.87ms
[E 2023-06-08 19:46:00.632 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.10) 258.97ms
[E 2023-06-08 19:59:35.308 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.4) 631.53ms
[E 2023-06-08 20:12:03.539 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.9) 226.09ms
[E 2023-06-08 20:12:29.357 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.4) 160.73ms
[E 2023-06-08 20:41:24.749 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.7) 220.95ms
[E 2023-06-08 20:41:44.609 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.7) 140.10ms
[E 2023-06-08 20:49:14.602 JupyterHub log:186] 500 GET /hub/oauth_callback?code=[secret]&state=[secret]&session_state=[secret] (@10.1.0.15) 331.61ms
```
</details>

**Comment by pnasrat** [comment] 2023-06-08 21:28
Froim log seems to be large no oauth errors. I don't see the standard http rate graphs I'd expect in grafana to look at error rates.

**Comment by pnasrat** [comment] 2023-06-08 21:33
Some pods triggered cluster growth by the look as we'd expect

https://grafana.utoronto.2i2c.cloud/d/Qx58n92nk/cluster-information?orgId=1&from=1686216758146&to=1686259958146&viewPanel=7

![image](https://github.com/2i2c-org/infrastructure/assets/13798/0fe2a047-e445-48db-ab95-fcdf1c461b44)

**Comment by pnasrat** [comment] 2023-06-08 21:34
Relevent node growth graph is https://grafana.utoronto.2i2c.cloud/d/Qx58n92nk/cluster-information?orgId=1&from=1686238436898&to=1686260036898&viewPanel=6

**Comment by pnasrat** [comment] 2023-06-08 21:37
Community reports widespread howver

```
kubectl get pods -n prod | grep jupyter- | wc -l
39
```

https://grafana.utoronto.2i2c.cloud/d/Qx58n92nk/cluster-information?orgId=1&from=1686238607471&to=1686260207471&viewPanel=3

**Comment by pnasrat** [comment] 2023-06-08 21:38
Both prod and r-prod spawn servers that work for me

**Comment by pnasrat** [comment] 2023-06-09 00:22
I was trying to do some explore queries of the hub for 500 but they weren't working

![image](https://github.com/2i2c-org/infrastructure/assets/13798/6f51ce48-772f-4118-8b74-aa217dc17c9c)

**Comment by pnasrat** [comment] 2023-06-09 00:35
```
 curl  http://localhost:8081/hub/metrics | grep code=\"5
jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="0.005",method="GET"} 0.0
jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="0.01",method="GET"} 0.0
1jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="0.025",method="GET"} 0.0
0jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="0.05",method="GET"} 0.0
0jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="0.075",method="GET"} 0.0
 jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="0.1",method="GET"} 0.0
 jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="0.25",method="GET"} 1.0
1jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="0.5",method="GET"} 4.0
2jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="0.75",method="GET"} 4.0
0jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="1.0",method="GET"} 4.0
kjupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="2.5",method="GET"} 4.0
 jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="5.0",method="GET"} 4.0
 jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="7.5",method="GET"} 4.0
1jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="10.0",method="GET"} 4.0
0jupyterhub_request_duration_seconds_bucket{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",le="+Inf",method="GET"} 4.0
0jupyterhub_request_duration_seconds_count{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",method="GET"} 4.0
 jupyterhub_request_duration_seconds_sum{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",method="GET"} 1.1942851543426514
 120k    jupyterhub_request_duration_seconds_created{code="500",handler="oauthenticator.oauth2.OAuthCallbackHandler",method="GET"} 1.6861702662246656e+09

```

**Comment by pnasrat** [comment] 2023-06-09 00:43
prod hub ip and node

```
kubectl get pod -n prod hub-749bb69658-fpk6n -o wide
NAME                   READY   STATUS    RESTARTS   AGE   IP            NODE                           NOMINATED NODE   READINESS GATES
hub-749bb69658-fpk6n   2/2     Running   0          38h   10.244.3.19   aks-core-34239724-vmss000006   <none>           <none>

```

**Comment by yuvipanda** [comment] 2023-06-09 06:40
Looking at the hub logs, I do see 500 errors during oauth callback. I see error messages that look like this:

```
Error fetching 400 POST https://login.microsoftonline.com/78aac226-2f03-4b4d-9037-b46d56c55210/oauth2/token: {
     "claims": "{\"access_token\":{\"<token>\":{\"essential\":true,\"values\":[\"<value>\"]}}}",
     "correlation_id": "8abad1e8-5676-497b-8705-b3d34b4c360c",
     "error": "interaction_required",
     "error_codes": [
      50158
     ],
     "error_description": "AADSTS50158: External security challenge not satisfied. User will be redirected to another page or authentication provider to satisfy additional authentication challenges.\r\nTrace ID: b95f7414-ee40-43b3-b8b7-b0f933a97f00\r\nCorrelation ID: 8abad1e8-5676-497b-8705-b3d34b4c360c\r\nTimestamp: 2023-06-09 05:19:50Z",
     "error_uri": "https://login.microsoftonline.com/error?code=50158",
     "suberror": "basic_action",
     "timestamp": "2023-06-09 05:19:50Z",
     "trace_id": "b95f7414-ee40-43b3-b8b7-b0f933a97f00"
    }
```

**Comment by yuvipanda** [comment] 2023-06-09 06:51
I've enabled 2FA on my utoronto.ca account, but can still login fine.

**Comment by yuvipanda** [comment] 2023-06-09 07:05
I do see a ton of these errors though: 
```
hub-logs prod | grep -c '500 GET' 
277
```

And they have been happening for a while: `​2023-06-07 21:41:15` UTC, and proceeding until `2023-06-09 05:19:50` UTC

**Comment by pnasrat** [comment] 2023-06-09 13:30
Possibly related #637 500s when credentials expire

**Comment by jsg-uoft** [comment] 2023-06-09 13:37
I wondered about that (especially since last time this came up we talked about changing the expiry date away from late August because that’s a lousy time). But it looks to me like we stuck with August last time again. I also looked at https://github.com/2i2c-org/infrastructure/issues/1687 which was caused by the secret being accidentally overwritten. Still not clear though.

Best

JG

On 2023-06-09, 9:31 AM, "Pris Nasrat" ***@***.***> wrote:

Possibly related #637 <https://github.com/2i2c-org/infrastructure/issues/637><https://github.com/2i2c-org/infrastructure/issues/637%3e> 500s when credentials expire

**Comment by pnasrat** [comment] 2023-06-09 13:56
@jsg-uoft yes, multiple issues could cause auth to fail, the error message is pretty clear it seems to be in the oauth flow.

`oauthenticator==15.1.0`

```pytb
    Traceback (most recent call last):
      File "/usr/local/lib/python3.11/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/oauthenticator/oauth2.py", line 222, in get
        user = await self.login_user()
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/handlers/base.py", line 810, in login_user
        authenticated = await self.authenticate(data)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/jupyterhub/auth.py", line 491, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/oauthenticator/azuread.py", line 69, in authenticate
        resp_json = await self.fetch(req)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/site-packages/oauthenticator/oauth2.py", line 387, in fetch
        raise e
      File "/usr/local/lib/python3.11/site-packages/oauthenticator/oauth2.py", line 366, in fetch
        resp = await self.http_client.fetch(req, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    tornado.httpclient.HTTPClientError: HTTP 400: Bad Request
****
```

**Comment by pnasrat** [comment] 2023-06-09 14:02
Looking at oauthenticator fetch we're in the error path, but it doesn't seem that the azure AD authenticator handles getting error: interaction_requred which it should according to

https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-error-codes#handling-error-codes-in-your-application

https://github.com/jupyterhub/oauthenticator/blob/15.1.0/oauthenticator/oauth2.py#L367

```json
 {
     "claims": "{\"access_token\":{\"capolids\":{\"essential\":true,\"values\":[\"XXX\"]}}}",
     "correlation_id": "REDACTED",
     "error": "interaction_required",
     "error_codes": [
      50158
     ],
     "error_description": "AADSTS50158: External security challenge not satisfied. User will be redirected to another page or authentication provider to satisfy additional authentication challenges.\r\nTrace ID: REDACTED
     \r\nCorrelation ID: REDACTED\r\nTimestamp: 2023-06-09 13:49:10Z",
     "error_uri": "https://login.microsoftonline.com/error?code=50158",
     "suberror": "basic_action",
     "timestamp": "2023-06-09 13:49:10Z",
     "trace_id": "REDACTED"
    }

```

**Comment by jsg-uoft** [comment] 2023-06-09 14:08
@pnasrat @yuvipanda could you confirm which login was used to generate the above error (AAD team are looking for it in the logs).

**Comment by yuvipanda** [comment] 2023-06-09 14:13
@jsg-uoft I'll share a username with you over freshdesk email to preserve user privacy, hang on.

**Comment by pnasrat** [comment] 2023-06-09 14:15
@jsg-uoft we don't have user logins in the logs as they are anonymized the logs contain correlation ids and user ids (hex)

**Comment by jsg-uoft** [comment] 2023-06-09 14:25
> @jsg-uoft we don't have user logins in the logs as they are anonymized the logs contain correlation ids and user ids (hex)

Ah, understood. Sorry, I thought the log entries were from one of you making the attempt!

**Comment by yuvipanda** [comment] 2023-06-09 14:32
@jsg-uoft I was able to repro this with my account on the staging hub, albeit not on the production hub. I've sent you the log + my user info on freshdesk.

**Comment by jsg-uoft** [comment] 2023-06-09 14:48
> Possibly related #637 500s when credentials expire

Confirmed credentials expire 31-Aug-2023.

**Comment by jsg-uoft** [comment] 2023-06-09 14:49
Our AAD team is proposing to open an Azure support case. Acknowledging @yuvipanda is in a very different time zone would one of you be available to join a call if possible?

**Comment by yuvipanda** [comment] 2023-06-09 14:52
@jsg-uoft I'm available for the next 2h. Can you co-ordinate with the support@ email and we'll try find someone to be available?

**Comment by jsg-uoft** [comment] 2023-06-09 14:53
Thank you @yuvipanda will coordinate via the support email.

**Comment by yuvipanda** [comment] 2023-06-09 20:57
I couldn't sleep, so I customized the error page to suggest users login to mail.utoronto.ca first and try again: https://2i2c.freshdesk.com/a/tickets/764

**Comment by yuvipanda** [comment] 2023-06-13 08:03
@pnasrat and @damianavila had a meeting with AzureAD support yesterday, and I think we're no closer to a solution than we were before. At this point, I strongly suggest we move to CILogon, via https://github.com/2i2c-org/infrastructure/pull/2641.

**Comment by yuvipanda** [comment] 2023-06-14 18:29
We have now moved entirely to CILogon! https://github.com/2i2c-org/infrastructure/pull/2641 has been merged, home directories have been migrated! \o/

**Comment by damianavila** [comment] 2023-06-23 15:52
Do you want to keep this one open to write some incident report, @yuvipanda?

**Comment by damianavila** [comment] 2023-07-06 21:23
Closing here, please reopen if you believe it is worth writing a report about this one.

**Closed by damianavila** 2023-07-06 21:23 UTC
