### ISSUE TITLE
Decomission hub -> cluster -> but also AWS account / GCP project?

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3870] opened 2024-03-27 13:42 UTC
Our docs to decomission doesn't mention cleaning up the AWS account / GCP project associated with the decomissioning.

Do we delete those as well as part of decomissioning a cluster, if not, when do we do that?

---

A real world example is about uw-hackweeks, we have a AWS account still that isn't used since #2173 and #3291 - do we delete it now?

**Comment by yuvipanda** [comment] 2024-03-27 21:28
Duplicate of https://github.com/2i2c-org/infrastructure/issues/3794

**Closed by yuvipanda** 2024-03-27 21:28 UTC
