### ISSUE TITLE
[Request deployment] New Hub: Kitware

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3906] opened 2024-04-03 17:41 UTC
## Phase 1: Account setup (**READY**)

This is applicable for cases where this is a dedicated cluster. The following table lists the information before this phase can start.

| Question | Answer |
| - | - |
| Cloud Provider | AWS |
| Will 2i2c pay for cloud costs and recover them via invoice? |  yes |
| Target Start Date | 2024-04-30 |
| Community Representatives | @annehaley @aashish24 |
| Technical Contacts added to Airtable? | No |

Docs at https://infrastructure.2i2c.org/hub-deployment-guide/cloud-accounts/

## Phase 2: Cluster setup (**READY**)

This assumes all engineers have access to this new account, and will be able to set up the cluster + support, without any new hubs being set up.

| Question | Answer | 
| - | - |
| Region / Zone of the cluster | us-west-2 | 
| Name of cluster | `kitware` | 
| Is GPU required? | Yes | 

Docs at https://infrastructure.2i2c.org/hub-deployment-guide/new-cluster/new-cluster/
and https://infrastructure.2i2c.org/hub-deployment-guide/deploy-support/configure-support/

## Phase 3 : Hub setup

There's going to be a number of hubs, and this starts specifying them.

#### Phase 3.1: Initial setup (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Name of the hub | staging | |
| Dask gateway? | no | |
| Splash image | https://www.kitware.com/main/wp-content/uploads/2021/10/Kitware-Wordmark.svg | |
| URL | https://www.kitware.com/  | Used for both URL and funded_by | 
| Authentication Mechanism | GitHub (via GitHubOAuthenticator) |
| Admin Users | @aashish24 @annehaley (**needs confirmation**) | 

At the end of this phase, both 2i2c engineers and the admin users mentioned can login to the hub.

#### Phase 3.2: Object storage access (**READY**)

| Question | Answer | Notes |
| - | - | - |
| Scratch bucket enabled? |  Yes |  |
| Persistent bucket enabled? | no |  |
| Requestor pays requests to external buckets allowed? | no | |  

#### Phase 3.3: Profile List (**READY**)

These are the standard profile list options we want to start with. Can be customized later

| Question | Answer | Notes |
| - | - | - |
| Pangeo Notebook?  |  Yes |  Use latest available date tag for [pangeo-notebook](https://quay.io/repository/pangeo/pangeo-notebook?tab=tags) |
| RStudio (with Rocker)? |  No  |  |
| Allow users to specify any image they want to use? | Yes | Enable `unlisted_choice`| 
| Max RAM option allowed | 30GB | Output of `deployer generate resource-allocation choices r5.xlarge --num-allocations 5` should be used |
| GPU enabled? | yes | |
| Default Interface | JupyterLab | |
| Allow multiple concurrent servers per user? | Yes | Translates to `allowNamedServers` |
 
#### Phase 3.4: Authentication tuning (**READY**)

| Question | Answer |
| - | - |
| Authentication Mechanism | GitHub (via GitHubOAuthenticator) |
| Org based access? | yes |
| List of GitHub orgs / teams to be granted access | [Pan3D Community](https://github.com/Pan3D-Community) |

#### Phase 3.5: Profile List finetuning (**NOT READY**)

| Question | Answer | Notes |
| - | - | - |
| Custom image to be specified?  | **needs answer** |  |

### Hub 2: kitware hub

The same as staging, just different name (kitware).

**Comment by colliand** [comment] 2024-04-03 17:42
FYI @aashish24, please share guidance on this issue as the 2i2c engineering team works to set up the Kitware hub.

**Comment by yuvipanda** [comment] 2024-04-03 19:11
I've also updated the issue to use our new new hub template, with clearer markers for what needs to be answered! Hope this is clearer :)

**Comment by colliand** [comment] 2024-04-03 20:29
Thanks @yuvipanda. I like the new format. I look forward to assistance on answering some of the questions above with input from @aashish24.

**Comment by yuvipanda** [comment] 2024-04-03 21:35
Based on additional information provided to me by @colliand, I've answered a bunch more questions in the issue. I think there are only two questions that need answering now!

**Comment by damianavila** [comment] 2024-04-04 16:02
Ask @GeorgianaElena to pair @yuvipanda on this one.

**Comment by yuvipanda** [comment] 2024-04-08 18:53
I'm going to be OOO this week, but I'd love for @GeorgianaElena to take the lead on this one + me providing review. And also get feedback on this issue structure.

**Comment by GeorgianaElena** [comment] 2024-04-10 14:24
- [x] Phase 1: Account setup is done
Also wanted to add the technical contacts in airtable, but wasn't sure if that was my job or not because it was asking for info I wasn't sure of, so I've just created an entry for the community and left it empty for now: https://airtable.com/appbjBTRIbgRiElkr/pag5pR65IDpx2Hyfv/recDKH0fNHnV4NfMu?uMtyG=b%3AWzAsWyI4WnV1VyIsOSxbInNlbDRjSG1pdlRuRlRza0ljIl0sIklPZVJqIl1d&home=pagog9egWRpeLyLGW
Might update it in later.

**Comment by GeorgianaElena** [comment] 2024-04-10 15:26
- [ ] Phase 2: Cluster and support  ready for review at https://github.com/2i2c-org/infrastructure/pull/3929

**Comment by johnkit** [comment] 2024-04-11 15:50
For user access/authentication, Kitware created a [Pan3D team](https://github.com/orgs/Kitware/teams/pan3d). @annehaley is the maintainer.

**Comment by annehaley** [comment] 2024-04-11 16:20
Thanks, @johnkit. I'll also add that our admin users should include @aashish24, @jourdain, and myself. 

I believe the last value we need to specify is the "custom image". @GeorgianaElena, could you clarify what is expected here? Does this refer to a docker image, AMI, or something similar? If we do not need a custom image, what would the default be? We may need to discuss our options as a team to find an appropriate answer.

**Comment by GeorgianaElena** [comment] 2024-04-12 11:18
Hi @johnkit and @annehaley 👋🏼 Thank you for the extra info 🚀 

> For user access/authentication, Kitware created a [Pan3D team](https://github.com/orgs/Kitware/teams/pan3d). @annehaley is the maintainer.

@johnkit, @annehaley can you please add me as an admin of the Kitware GitHub organization? I will remove myself after the authentication is setup. [Documentation](https://infrastructure.2i2c.org/hub-deployment-guide/configure-auth/github-orgs/#get-admin-access-to-the-target-organisation) about the reason behind this request.

Alternatively, we need to make sure that an admin of the organization accesses the hub and approves the OAuth app like described in [this section](https://infrastructure.2i2c.org/hub-deployment-guide/configure-auth/github-orgs/#granting-access-to-the-oauth-app).

> If we do not need a custom image, what would the default be?

The hub will be setup to present a profile list, from the users can choose which Docker image to start in their server. If you don't provide a custom image at this point in the setup process, there's no problem, we can always add it later.
Without it, by default the profile list will present two image options:
-  The latest available date tag for [pangeo-notebook](https://quay.io/repository/pangeo/pangeo-notebook?tab=tags)
- A custom "Other" option where you can type in the link towards a docker image of your choice.

Something similar to  (this one has 3 pre-defined options and a custom one where you can directly input an image):
<img width="573" alt="Screenshot 2024-04-12 at 11 53 38" src="https://github.com/2i2c-org/infrastructure/assets/7579677/05a5ef63-6e9e-45f1-ba9c-57d66b8813cb">

> I believe the last value we need to specify is the "custom image". @GeorgianaElena, could you clarify what is expected here?

@annehaley, this is a Docker image that will be presented to the users as a pre-defined profile list option and this image is what will be used to define the user server environment. There are [docs about this custom image](https://docs.2i2c.org/admin/howto/environment/#create-your-own-docker-image) and at the end of this doc it links to [a step-by-step guide](https://docs.2i2c.org/admin/howto/environment/hub-user-image-template-guide/#hub-user-image-template-guide-how-to) on how to quickly create a GitHub repository to host and build from this docker image.
There is also [a runbook](https://docs.2i2c.org/how-to-guides/add-packages-to-image/) on how to later add packages to this image.

**Comment by johnkit** [comment] 2024-04-12 17:27
I apologize @GeorgianaElena . I jumped the gun on this, and after more internal discussion, we are going to instead create a new github organization for access control. We'll do that Monday or Tuesday after all of the Kitware stakeholders have weighed in. Again I am sorry for the inconvenience and delay.

**Comment by annehaley** [comment] 2024-04-16 16:38
@GeorgianaElena Thank you for the explanation about the image. I think it would be appropriate to select the default base image at this stage. The `pangeo-notebook` image will have most of what we need. 
There are a few extra requirements we will need to install, though. When we launch with MyBinder, we have a `requirements.txt` and a `postBuild` script that we need to run: https://github.com/Kitware/pan3d/tree/main/.binder. Will it be possible to accomplish something similar without creating a custom image?

**Comment by johnkit** [comment] 2024-04-17 14:24
This morning we created the [Pan3D Community](https://github.com/Pan3D-Community) Github organization for controlling access to the Kitware hub and other resources. @GeorgianaElena has been invited with owner access.

**Comment by GeorgianaElena** [comment] 2024-04-17 14:59
> This morning we created the [Pan3D Community](https://github.com/Pan3D-Community) Github organization for controlling access to the Kitware hub and other resources. @GeorgianaElena has been invited with owner access.

Thank you very much @johnkit. Will proceed with the deploy and let you all know when a hub will be available for testing or if there's any info missing.

> There are a few extra requirements we will need to install, though. When we launch with MyBinder, we have a requirements.txt and a postBuild script that we need to run: https://github.com/Kitware/pan3d/tree/main/.binder. Will it be possible to accomplish something similar without creating a custom image?

@annehaley, this will require creating a new image. But the guide at https://docs.2i2c.org/admin/howto/environment/#create-your-own-docker-image should provide all the steps needed for how to create one super quickly. Let me know if I can help out with anything.

In the meantime, I will start deploying an initial hub with the default image, and we can add the custom on later without any problem.

**Comment by GeorgianaElena** [comment] 2024-04-18 08:55
@johnkit, @annehaley, I've deployed a staging hub at https://staging.kitware.2i2c.cloud/ that you can now test 🎉 

I will also deploy a production one today. Once you confirm that you can login, start a server and that overall everything looks like expected, I believe we can close this issue and continue discussing about adding a second profile option with the custom image via our support process https://docs.2i2c.org/support/.

**Comment by johnkit** [comment] 2024-04-18 14:04
Yes! @GeorgianaElena I confirmed that I can connect to the staging hub, start a server, create/interact with notebooks, etc. Thanks!

**Comment by annehaley** [comment] 2024-04-18 14:06
Thank you, @GeorgianaElena. I'll start on the new custom image today.

**Comment by GeorgianaElena** [comment] 2024-04-18 16:51
>Thank you, @GeorgianaElena. I'll start on the new custom image today.

Thanks @annehaley 🚀 

> Yes! @GeorgianaElena I confirmed that I can connect to the staging hub, start a server, create/interact with notebooks, etc. Thanks!

Yay 🎉 

There's also https://kitware.2i2c.cloud/ that's ready to be tried.

**Comment by johnkit** [comment] 2024-04-22 14:51
Also confirmed that I can connect to https://kitware.2i2c.cloud/ and create notebooks there too. Thanks again.

**Comment by yuvipanda** [comment] 2024-04-30 18:16
Everything except setting up the custom image @annehaley is building is set up by now, right?

**Comment by annehaley** [comment] 2024-05-01 12:55
@yuvipanda Yes, I have just finished the new custom image. It was published yesterday: [kitware/trame:geotrame-cloud](https://hub.docker.com/layers/kitware/trame/geotrame-cloud/images/sha256-744a96f9e94f2606fcd734919051b0787d946567471d18c44f6b7dfe890152ff). Could you please add this to the deployment so we can test it?

**Comment by yuvipanda** [comment] 2024-05-01 19:19
@annehaley try it out now?

**Comment by annehaley** [comment] 2024-05-01 19:54
@yuvipanda That works, thank you! I can now run our example notebooks.

**Comment by yuvipanda** [comment] 2024-05-01 20:11
Perfect! I'm going to close this issue as done now. Please email `support@2i2c.org` with any further questions / modifications you may need. Excited to see this moving forward!

**Closed by yuvipanda** 2024-05-01 20:11 UTC
Labels: new hub
