### ISSUE TITLE
Document how to scale up nodes/node pools for an event

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1628] opened 2022-08-15 12:26 UTC
### Context

I believe I am responsible for https://github.com/2i2c-org/infrastructure/issues/1576 but I've never scaled up a hub for an event before so I went looking for docs but couldn't find any.

We should:

- Document the steps required for scaling up a hub prior to an event
- For the case of event hubs on shared clusters, I believe we add a specific node pool and label via terraform? We should document that too.

**Comment by GeorgianaElena** [comment] 2022-08-18 13:09
@sgibson91, I believe this might be a dupe of https://github.com/2i2c-org/infrastructure/issues/787 and to some extent of https://github.com/2i2c-org/infrastructure/issues/1594.

> I believe I am responsible for https://github.com/2i2c-org/infrastructure/issues/1576 but I've never scaled up a hub for an event before so I went looking for docs but couldn't find any.

And since I've also found myself into this situation recently, I would like to signal boost the importance of having these docs for the two issues I linked above and really think that we should prioritize these tasks.

**Comment by sgibson91** [comment] 2022-08-18 14:38
Ah, I probably didn't use the right search term before opening an issue! Shall we close in favour or #787 and signal boost there?

**Comment by damianavila** [comment] 2022-08-23 02:11
Closing this one and raising the priority on #787.

**Closed by damianavila** 2022-08-23 02:11 UTC
