### ISSUE TITLE
Enable UC Merced hub users to select between R and Python focused images

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3188] opened 2023-09-28 17:20 UTC
### Context

UC Merced is working through a pilot with a 2i2c operated education hub service. The pilot involves courses that use R and Python. The software image that 2i2c uses to delivery R and Python is bloated and difficult to keep up to date. The situation is reminiscent of prior experience with the University of Toronto.  Merced may wish to move over to multi-hub service after the pilot but wants to complete the current engagement using a single hub. The 2i2c team discussed some scenarios and shared recommendations with Merced.

### Proposal

Change from the current single R + Python image to offer an image selector after login with a menu offering Merced hub users to choose between two images: an up-to-date Python-focused image and an up-to-date R-focused image. 

Merced personnel have been notified that the menu is likely to create some confusion among hub users. Some students intending to work on Python related work will mistakenly select the R image, etc. Merced is developing communications and local support plans to address these risks. Merced requests that 2i2c provide a precise data and time when this change will be deployed.  Merced asked if this change could be done during the week of October 2 or October 9. @colliand indicated he'd respond with a precise date pending a capacity review by 2i2c's Engineering Team. FYI @damianavila.

**Comment by yuvipanda** [comment] 2023-09-28 17:50
Let's use the `jupyter/scipy-notebook` image for python, and perhaps the `rocker/binder` image for R. However, neither of these actually have `nbgitpuller` in them, which can be problematic if they are using it. I had opened https://github.com/jupyter/docker-stacks/pull/2000 to put nbgitpuller in jupyter docker-stacks.

There's no staging hub for UC merced - I think perhaps we should change that too #3150 so we can deploy things there for them to test. I think that's the easiest way to do this.

**Comment by yuvipanda** [comment] 2023-09-28 19:03
Here's what I think is the easiest, least stressful thing for engineers to do:

1. Deploy a uc-merced staging hub (#3150)
2. Set it up to have new images
3. Have UC Merced folks to test it
4. Once they are satisfied, move that to the prod hub

Given the primary reason this is happening is because we're retiring the image we maintain that has both R and python, I think this is the easiest way to do.

**Comment by yuvipanda** [comment] 2023-09-28 19:49
I'm happy to provide review but would like someone else to be assigned to this :)

**Comment by colliand** [comment] 2023-10-02 20:30
Thanks @yuvipanda! FYI @damianavila I need to reply to Sarvani with a date when the service will change to include the R + Python images drop-down menu. She asked me via text today.

**Comment by damianavila** [comment] 2023-10-02 22:15
@GeorgianaElena is going off the support triage cycle on Tuesday, so I assigned her this one to be worked on during the Wed-Fri period of this week. I also count on @yuvipanda to provide Georgina with any help she might need.

**Comment by colliand** [comment] 2023-10-03 15:16
Thanks @GeorgianaElena. I add @schadalapaka to the thread so that she can follow along with our progress. I expect she and her colleagues will like the plan to launch a staging hub and use it for testing prior to deploying big changes to production. Sarvani, let's aim to complete the testing of the staging hub on October 9 (more ambitiously on October 6). If that all looks good, let's pencil in the plan to deploy to production on October 12. It's never a good idea to deploy big changes on Friday!

**Comment by schadalapaka** [comment] 2023-10-03 18:42
Hi All -
Thank you for the notes.
I have reached out to our instructors to find out their availability to test this implementation on staging hub from Oct 9-11.
I will share updates as I have them.

Regards
Sarvani

**Comment by schadalapaka** [comment] 2023-10-03 20:55
Hi All -

Oct 9- 11th works for us to test. However, we request you move implementation after 9:30 am PT on the 13th to avoid conflicting with a course final exam.
In addition, when it is ready, please share instructions on how we can access the staging hub.

Hope this helps, please do not hesitate to let me know if you have any additional questions at this time.

Regards,
Sarvani

**Comment by damianavila** [comment] 2023-10-03 21:42
> Oct 9- 11th works for us to test. However, we request you move implementation after 9:30 am PT on the 13th to avoid conflicting with a course final exam.

Given this additional context, I would suggest extending the test period from Oct 9 - Oct 13, so the instructors have the whole week to test it and then we deploy it into production on Oct 16th.

**Comment by schadalapaka** [comment] 2023-10-04 15:19
I will check with our instructors.
Also, question: How long do you estimate the deployment takes?

**Comment by GeorgianaElena** [comment] 2023-10-04 15:30
@schadalapaka, there is now a staging hub running at https://staging.ucmerced.2i2c.cloud/hub/spawn, which allows the option to choose between a Python or a R user environment.

Choosing the Python image, will launch the users into JupyterLab, whereas choosing the R image will redirect them to RStudio after the server is started. Does this sound ok @schadalapaka, or would you like to use JupyterLab as the default redirect for both options, and then let the users choose to launch RStudio from there, like it's happening right now?

**Comment by schadalapaka** [comment] 2023-10-04 21:44
Hi All-
1. Let’s stick to the original schedule for testing on staging hub from Oct 9-12 and making changes on deployment server on the 13th after 9:30 am.
2. I think a jupyterlab with a default redirect for both options, and letting users choose between Python or R image would be good.

**Comment by schadalapaka** [comment] 2023-10-06 15:20
1. I will inform our users about a potential confusion spots.
2. Thank you for the screen grab. I will share it with our users.

**Comment by yuvipanda** [comment] 2023-10-06 17:06
@schadalapaka yes the staging hub is ready for your users to start testing, using the link from https://github.com/2i2c-org/infrastructure/issues/3188#issuecomment-1747131261

**Comment by schadalapaka** [comment] 2023-10-10 18:05
Hi All -
From our users:
Testing out the image and one big problem: notebooks do not save as .pdf files.  This is beyond the usual problem that files with documentation don't save (I think someone hasn't added the correct font), they don't save at all.  I've attached the error screen.
![image](https://github.com/2i2c-org/infrastructure/assets/31516936/cbd98579-3aa1-4ef4-b468-3accaf697d0a)

Please let me know if this is an expected behavior.

Regards,
Sarvani

**Comment by yuvipanda** [comment] 2023-10-10 18:34
@schadalapaka Can you share (privately to support@2i2c.org if necessary) the notebook that caused this? I just tried a simple notebook (just `print("Hello world")`) and it was able to export to PDF just fine.

**Comment by yuvipanda** [comment] 2023-10-10 18:44
@schadalapaka ah, so I can reproduce this if I'm using the *R* image. PDF works fine in the Python image. Maybe starting RStudio by default from the R image may reduce this confusion? Do your users use R from JupyterLab?

**Comment by consideRatio** [comment] 2023-10-12 21:52
@schadalapaka the 13th is tomorrow and I'm not sure on what to do, but I see three short term choices available:

1. To transition what's on [staging](https://staging.ucmerced.2i2c.cloud) to [production](https://ucmerced.2i2c.cloud) as it is on the 13th after 9:30 am PT
2. Make the change suggested by Yuvi above, making to start R image users directly into RStudio, and put that to [production](https://ucmerced.2i2c.cloud) the 13th after 9:30 am PT
3. To do nothing for now and take more time to finding a path forward

**Comment by schadalapaka** [comment] 2023-10-13 06:11
Hi All -
Thank you for the notes.
Yes, I think starting RStudio by default would reduce the confusion. 

I think the next best step is for Yuvi to make the changes in the staging hub. 
We can then have our users test it for a few more days before deciding on a new deployment date. 
I'm worried that making this change on the production server tomorrow won't give our users enough time to test it properly.

Please let me know if this works and/or if there is any concerns with this approach.
Do let me know if there is any additional information I might provide at this time.

**Comment by GeorgianaElena** [comment] 2023-10-13 10:32
@schadalapaka, allowing for the users to test this more thoroughly and accommodate to the changes makes sense.

I've updated the staging hub to start in RStudio by default when choosing the R image.

Take the time to see how this works and please let us know when you know the new deployment to production date so we can plan around it.

**Comment by schadalapaka** [comment] 2023-10-16 18:31
Hi All -
Our researchers have said that this Friday(10/20) after 9:30 am PT would work best for them.

**Comment by schadalapaka** [comment] 2023-10-16 22:06
Another note: At this time, there doesn't seem to be an easy way for users to switch between python and R images easily. Once we choose an image, we have to break the urls to be able to stop the server and only then will we see an option to switch to another image or select between the images. 
Would it be possible to fix this?

**Comment by schadalapaka** [comment] 2023-10-16 22:50
Notes from our staging hub testers:
- My notebooks, most likely because they're .ipynb files, appear to load as code rather than R scripts
- The notebooks can load into RStudio but the original R code is buried under a mess of formatting.  Is this what's going to happen to all our notebooks when we switch over?
- My notebooks, most likely because they're .ipynb files, appear to load as code rather than R scripts
- 
![image](https://github.com/2i2c-org/infrastructure/assets/31516936/867fb73f-e37b-4ac5-9108-dfb50240a594)

**Comment by yuvipanda** [comment] 2023-10-17 13:39
@schadalapaka let me summarize current state of issues:

1. Opening `.ipynb` files in RStudio doesn't really work. This is expected, as RStudio uses a different notebook format (`.Rmd`) not `.ipynb` files. Our earlier *assumption* was that most of the R users were using RStudio (and hence `.Rmd` files or `.R` files), *not* JupyterLab with `.ipynb` files. Is this inaccurate? Do your R users want to use *both* RStudio and JupyterLab *for R*? Or perhaps they don't want RStudio *at all*? So the question here is: "Do R users want JupyterLab with R as well as RStudio with R? Or only JupyterLab with R? Or only RStudio with R?"
2. > Once we choose an image, we have to break the urls to be able to stop the server and only then will we see an option to switch to another image or select between the images. 
    Unfortunately there really isn't. This is why we recommend separate hubs for R and python for most cases. This is the primary confusion that users will run into. We can allow users to have *multiple* servers running at the same time, but in our experience, especially for educational use cases, this usually causes *more* confusion, not less. Multiple hubs at different URLs is often the way to go, and where I hope UC Merced eventually goes. My understanding is that this image selection is a temporary fix, as the contract probably needs to be different for multiple hubs.
3. > Going back to the pilot hub, attempting to open an .ipynb notebook in RStudio gets the "File is binary rather than text so cannot be opened by the source editor" error. I am worried that if we go over to this image we will lose access to all our previous Jupyter notebooks.
     This is because the pilot hub's RStudio version is *really* old. And also (1), where `.ipynb` files can not be opened by RStudio.

What do you think about a 30min call tomorrow Oct 18 9AM pacific (or earlier, if possible - I'm currently traveling in India, and @GeorgianaElena is in the EU) to clear things up?

**Comment by colliand** [comment] 2023-10-17 14:09
I can also be available for a call with @schadalapaka. This experience of R versus Python user confusion was anticipated and is a main reason why the multi-hub approach is better than image select drop-down for education scenarios. Thanks @yuvipanda for your generosity and clarity.

**Comment by colliand** [comment] 2023-10-18 15:16
Default back to RStudio? I'm confused by what @yuvipanda wrote above.

**Comment by yuvipanda** [comment] 2023-10-18 15:18
@colliand sorry, I menat default back to JupyterLab. Edited to fix.

**Comment by yuvipanda** [comment] 2023-10-18 15:20
https://github.com/2i2c-org/infrastructure/pull/3290 moves the hub back to using JupyterLab as the default interface, and https://github.com/2i2c-org/infrastructure/issues/3289 tracks fixing PDF generation in jupyterlab in the R image. I've opened https://github.com/rocker-org/rocker-versioned2/pull/714 upstream to fix that.

So to recap:

1. The default interface for *both the Python and R image* will be *JupyterLab*
2. We'll work on fixing the PDF generation in JupyterLab in the R image before rollout. Investigation is over and upstream PR has already been sent.
3. Users wanting to use RStudio specifically can still launch it explicitly if needed.

**Comment by yuvipanda** [comment] 2023-10-18 15:29
@schadalapaka ok, so everything *except* PDF conversion in R is ready for testing again. That should be hopefully sorted in a day or two.

**Comment by colliand** [comment] 2023-10-18 15:56
Thanks Yuvi for highlighting item 3 above: _Users wanting to use RStudio specifically can still launch it explicitly if needed._

**Comment by yuvipanda** [comment] 2023-10-20 17:11
@schadalapaka @colliand we worked with upstream (https://github.com/rocker-org/rocker-versioned2/pull/714) and now PDF generation works fine from inside Jupyter as well! So from our perspective the staging hub is now good to go - please keep us posted on when we can flip the switch.

**Comment by colliand** [comment] 2023-10-20 18:12
I love that feedback from Merced to 2i2c identified an upstream bug and that 2i2c has deployed upstream changes to fix the big! Thanks Merced and 2i2c engineering for making the open source ecosystem better.

**Comment by schadalapaka** [comment] 2023-10-25 22:53
Dear All -

2i2c can deploy changes to production after Friday 9:30 am.

**Comment by schadalapaka** [comment] 2023-10-26 18:09
Hi All -
Another question. With this new implementation, how do I access shell terminal?

**Closed** 2023-10-29 07:36 UTC
